### ISSUE TITLE
Readonly error 1.9

### ISSUE THREAD

**Issue by wsmoses** [EnzymeAD/Enzyme.jl#486]
```julia
using Enzyme

Enzyme.API.printall!(true)
    struct LList
        next::Union{LList,Nothing}
        val::Float64
    end

    function sumlist(n::LList, len)
        sum = 0.0
        # while n !== nothing
        for i in 1:len
            sum += n.val
            n = n.next
        end
        sum
    end

    regular = LList(LList(nothing, 1.0), 2.0)
    shadow  = LList(LList(nothing, 0.0), 0.0)
    ad = autodiff(Reverse, sumlist, Active, Duplicated(regular, shadow), 2)
    ```
    
If the dynamic_size_workaround is enabled this works, using the dynamic size gc alloc, however, fails.
 In other

**Comment by vchuravy** [comment]
```
(gdb) bt
#0  gc_big_object_link (list=0x330bff8, hdr=0x7fff9e4da040) at /cache/build/default-amdci4-0/julialang/julia-master/src/gc.h:504
#1  jl_gc_big_alloc_inner (sz=78798288, ptls=0x330bdc0) at /cache/build/default-amdci4-0/julialang/julia-master/src/gc.c:1003
#2  ijl_gc_big_alloc (ptls=0x330bdc0, sz=78798288) at /cache/build/default-amdci4-0/julialang/julia-master/src/gc.c:1010
#3  0x00007ffff7d281bf in ?? ()
#4  0x0000000000000000 in ?? ()
(gdb) 
```

**Comment by vchuravy** [comment]
```
#0  gc_big_object_link (list=0x3aaa878, hdr=0x7fff9cb0d040) at /cache/build/default-amdci4-0/julialang/julia-master/src/gc.h:504
#1  jl_gc_big_alloc_inner (sz=105850496, ptls=0x3aaa640) at /cache/build/default-amdci4-0/julialang/julia-master/src/gc.c:1003
#2  ijl_gc_big_alloc (ptls=0x3aaa640, sz=105850496) at /cache/build/default-amdci4-0/julialang/julia-master/src/gc.c:1010
#3  0x00007ffff7d281bf in julia_sumlist_1718 (n=..., len=<optimized out>) at /home/vchuravy/src/Enzyme/test.jl:12
#4  0x00007ffff7d281bf in julia_sumlist_1718 (n=..., len=<optimized out>)
#5  0x00007fffdefa9173 in macro expansion () at /home/vchuravy/src/Enzyme/src/compiler.jl:6071
#6  julia_enzyme_call_3386 (fptr=140737342231360, tt=<optimized out>, rt=<optimized out>, f=..., df=..., args...=...) at /home/vchuravy/src/Enzyme/src/compiler.jl:5802
#7  0x00007fffdefa91af in jfptr_enzyme_call_3387 ()
#8  0x00007ffff744305e in _jl_invoke (world=<optimized out>, mfunc=0x7fffee400c90, nargs=13, args=0x7fffffffb888, F=0x7fffeda3af98)
    at /cache/build/default-amdci4-0/julialang/julia-master/src/gf.c:2446
#9  ijl_apply_generic (F=<optimized out>, args=args@entry=0x7fffffffb888, nargs=<optimized out>) at /cache/build/default-amdci4-0/julialang/julia-master/src/gf.c:2628
#10 0x00007ffff7453bb1 in jl_apply (nargs=<optimized out>, args=0x7fffffffb880) at /cache/build/default-amdci4-0/julialang/julia-master/src/julia.h:1866
#11 do_apply (args=<optimized out>, nargs=<optimized out>, iterate=0x7fffe292f270 <jl_system_image_data+4853616>) at /cache/build/default-amdci4-0/julialang/julia-master/src/builtins.c:730
#12 0x00007fffdefa1265 in japi1_CombinedAdjointThunk_3304 (thunk=..., args...=0x7fffa5c181f0) at /home/vchuravy/src/Enzyme/src/compiler.jl:5779
#13 0x00007ffff744305e in _jl_invoke (world=<optimized out>, mfunc=0x7fffedcde540, nargs=3, args=0x7fffffffbb58, F=0x7fffbf2417f0)
    at /cache/build/default-amdci4-0/julialang/julia-master/src/gf.c:2446
#14 ijl_apply_generic (F=<optimized out>, args=args@entry=0x7fffffffbb58, nargs=<optimized out>) at /cache/build/default-amdci4-0/julialang/julia-master/src/gf.c:2628
#15 0x00007ffff7453bb1 in jl_apply (nargs=<optimized out>, args=0x7fffffffbb50) at /cache/build/default-amdci4-0/julialang/julia-master/src/julia.h:1866
#16 do_apply (args=<optimized out>, nargs=<optimized out>, iterate=0x7fffe292f270 <jl_system_image_data+4853616>) at /cache/build/default-amdci4-0/julialang/julia-master/src/builtins.c:730
#17 0x00007ffff1b4c29a in japi1_autodiff_641 (f=..., args...=<optimized out>) at /home/vchuravy/src/Enzyme/src/Enzyme.jl:317
```
